### ISSUE TITLE
html v2

### ISSUE THREAD

**Issue by bukzor** [davidmalcolm/gcc-python-plugin#7]
This is a big-ticket to get the revamped html into a usable-by-default state.

This is blocked by four tasks:
- [x] #8 remove lxml dependency
- [x] #9 generate by default
- [x] #10 inline html depdendencies
- [x] #11 optimize size a little

@davidmalcolm Could you review this plan and let me know if it needs to be altered and/or what order you'd like to see these four patches? I'll start work after I hear the go-ahead.
